language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell

env:
  global:
    - CIBW_SKIP="cp27-*"
    - TWINE_USERNAME=codypiersall
    - CIBW_TEST_REQUIRES="pytest pytest-asyncio pytest-trio trio"
    - CIBW_TEST_COMMAND="pytest -s -v {project}/test"

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
