services:
  - docker

install:
  - docker pull codypiersall/manylinux1-pynng
  - mkdir artifacts

script:
  - docker run -v "$(pwd)/artifacts:/mnt/artifacts" --rm -i -t codypiersall/manylinux1-pynng bash -x -c "cd && git clone https://github.com/codypiersall/pynng && cd pynng && git checkout dockerbuild && ./build_in_docker.sh"
  - ls artifacts/dist

